# Generated by Django 2.0 on 2019-01-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0005_auto_20181207_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
