# Generated by Django 2.0 on 2019-01-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0006_auto_20190104_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
