# Generated by Django 2.0 on 2019-01-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0008_auto_20190122_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
