# Generated by Django 2.0 on 2019-01-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0009_auto_20190123_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
