# Generated by Django 2.0 on 2019-05-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0010_auto_20190123_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packing',
            name='delete_state',
        ),
    ]
