# Generated by Django 2.0 on 2019-05-14 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0080_auto_20190514_1554'),
        ('packing', '0011_remove_packing_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('packingCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='packing.PackingCode')),
                ('productCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.ProductCode')),
            ],
        ),
        migrations.AddField(
            model_name='packing',
            name='autoRelease',
            field=models.CharField(blank=True, choices=[('자동출고', '자동출고'), ('수동출고', '수동출고')], max_length=10, null=True),
        ),
    ]
