# Generated by Django 2.0 on 2019-09-05 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0086_auto_20190905_1055'),
        ('packing', '0012_auto_20190514_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='productCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.Product'),
        ),
    ]
