# Generated by Django 2.0 on 2018-10-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=255)),
                ('delete_state', models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2)),
                ('location_address', models.CharField(max_length=255)),
                ('location_phone', models.CharField(max_length=255)),
                ('location_companyNumber', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('01', '포장재입고'), ('03', '원란입고'), ('05', '판매'), ('07', '원란판매'), ('09', 'OEM입고거래처')], default='05', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
