# Generated by Django 2.0 on 2018-11-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181004_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
