# Generated by Django 2.0 on 2018-10-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181004_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='expiration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcode',
            name='vat',
            field=models.IntegerField(default=0),
        ),
    ]
