# Generated by Django 2.0 on 2018-10-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20181004_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcode',
            name='amount_kg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='price',
            field=models.IntegerField(),
        ),
    ]
