# Generated by Django 2.0 on 2018-10-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20181004_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcode',
            name='type',
            field=models.CharField(choices=[('전란', '전란'), ('난백', '난백'), ('난황', '난황'), ('X', '없음')], default='', max_length=10),
        ),
    ]
