# Generated by Django 2.0 on 2018-10-10 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20181008_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='purchaseYymd',
        ),
        migrations.AddField(
            model_name='product',
            name='purchaseYmd',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='loss_clean',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='loss_fill',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchaseLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_locationCode', to='core.Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchaseLocationName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='total_loss_clean',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='total_loss_fill',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='total_loss_insert',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='total_loss_openEgg',
            field=models.IntegerField(default=0),
        ),
    ]
