# Generated by Django 2.0 on 2018-10-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20181019_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunitprice',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
