# Generated by Django 2.0 on 2018-11-05 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20181105_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadmin',
            name='delete_state',
            field=models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
