# Generated by Django 2.0 on 2018-11-20 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20181120_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunitprice',
            name='specialPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
