# Generated by Django 2.0 on 2018-12-20 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_auto_20181217_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='oem',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
