# Generated by Django 2.0 on 2019-01-07 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_auto_20181220_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadmin',
            name='releaseType',
            field=models.CharField(choices=[('생성', '생성'), ('판매', '판매'), ('샘플', '샘플'), ('증정', '증정'), ('자손', '자손'), ('반품', '반품'), ('이동', '이동'), ('미출고품사용', '미출고품사용'), ('재고조정', '재고조정')], default='생성', max_length=10),
        ),
        migrations.AlterField(
            model_name='productegg',
            name='type',
            field=models.CharField(choices=[('할란', '할란'), ('할란사용', '할란사용'), ('공정품투입', '공정품투입'), ('공정품발생', '공정품발생'), ('미출고품사용', '미출고품사용'), ('미출고품투입', '미출고품투입')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
