# Generated by Django 2.0 on 2018-12-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0003_auto_20181207_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
