# Generated by Django 2.0 on 2018-12-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0006_auto_20181207_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
