# Generated by Django 2.0 on 2018-12-26 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location_location_owner'),
        ('eggs', '0008_auto_20181226_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='in_locationCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_location', to='core.Location'),
        ),
        migrations.AddField(
            model_name='egg',
            name='in_locationCodeName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
