# Generated by Django 2.0 on 2018-12-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0009_auto_20181226_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='in_ymd',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
