# Generated by Django 2.0 on 2019-01-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0012_auto_20181227_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
