# Generated by Django 2.0 on 2019-01-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0013_auto_20190108_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
