# Generated by Django 2.0 on 2019-01-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0014_auto_20190116_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='amount_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
    ]
