# Generated by Django 2.0 on 2019-01-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0015_auto_20190122_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
