# Generated by Django 2.0 on 2019-06-27 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location_location_owner'),
        ('eggs', '0018_remove_egg_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymd', models.CharField(max_length=8, verbose_name='날짜')),
                ('code', models.CharField(max_length=255, verbose_name='코드')),
                ('codeName', models.CharField(max_length=255, verbose_name='코드명')),
                ('orderCount', models.IntegerField(verbose_name='지시량')),
                ('realCount', models.IntegerField(blank=True, null=True, verbose_name='실제출하량')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='지시자메모')),
                ('site_memo', models.TextField(blank=True, null=True, verbose_name='현장메모')),
                ('in_ymd', models.CharField(max_length=8, verbose_name='입고일')),
                ('in_locationCodeName', models.CharField(max_length=255, verbose_name='입고처명')),
                ('display_state', models.CharField(choices=[('Y', '진행중'), ('N', '마감')], default='Y', max_length=10)),
                ('eggCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eggs.EggCode')),
                ('in_locationCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Location')),
            ],
        ),
    ]
