# Generated by Django 2.0 on 2019-05-24 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eggs', '0018_auto_20190524_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggOrderMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymd', models.CharField(max_length=8)),
                ('finish', models.CharField(choices=[('Y', 'finished'), ('N', 'notfinished')], default='N', max_length=2)),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='eggorder',
            name='commander',
        ),
        migrations.AddField(
            model_name='eggorder',
            name='orderMaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eggs.EggOrderMaster'),
        ),
    ]
