# Generated by Django 2.0 on 2019-05-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0020_auto_20190524_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggorder',
            name='realCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
