# Generated by Django 2.0 on 2019-05-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0021_auto_20190524_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggordermaster',
            name='commander',
        ),
        migrations.RemoveField(
            model_name='eggorder',
            name='orderMaster',
        ),
        migrations.AlterField(
            model_name='eggorder',
            name='realCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='실제출하량'),
        ),
        migrations.DeleteModel(
            name='EggOrderMaster',
        ),
    ]
