# Generated by Django 2.0 on 2019-05-31 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0022_auto_20190531_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggorder',
            name='priority',
        ),
    ]
