# Generated by Django 2.0 on 2019-08-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0025_auto_20190610_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggorder',
            name='display_state',
            field=models.CharField(choices=[('Y', '진행중'), ('N', '마감')], default='Y', max_length=10),
        ),
    ]
