# Generated by Django 2.0 on 2018-10-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('code_name', models.CharField(max_length=255)),
                ('delete_state', models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2)),
                ('amount_kg', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('전란', '전란'), ('난백', '난백'), ('난황', '난황'), ('', '없음')], default='', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
