# Generated by Django 2.0 on 2018-10-04 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181002_1700'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymd', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=255)),
                ('codeName', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('memo', models.TextField()),
                ('delete_state', models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2)),
                ('loss_clean', models.FloatField()),
                ('loss_fill', models.FloatField()),
                ('purchaseYymd', models.CharField(max_length=8)),
                ('purchaseLocationName', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('ymd', models.CharField(max_length=8)),
                ('releaseType', models.CharField(choices=[('판매', '판매'), ('샘플', '샘플'), ('증정', '증정'), ('자손', '자손'), ('이동', '이동')], default='', max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductEgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymd', models.CharField(max_length=8)),
                ('type', models.CharField(choices=[('할란', '할란'), ('할란사용', '할란사용'), ('공정품투입', '공정품투입'), ('공정품발생', '공정품발생')], default='', max_length=30)),
                ('tank', models.CharField(choices=[('01201', 'RAW Tank 전란'), ('01202', 'RAW Tank 난황'), ('01203', 'RAW Tank 난백'), ('01204', 'Past Tank 전란'), ('01205', 'Past Tank 난황'), ('01206', 'Past Tank 난백'), ('01207', 'RAW Tank 등급란 전란'), ('01208', 'RAW Tank 등급란 난황'), ('01209', 'RAW Tank 등급란 난백')], default='01201', max_length=10)),
                ('rawTank_amount', models.IntegerField()),
                ('pastTank_amount', models.IntegerField()),
                ('loss_insert', models.FloatField()),
                ('loss_openEgg', models.FloatField()),
                ('memo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_id', models.IntegerField()),
                ('ymd', models.CharField(max_length=8)),
                ('total_loss_openEgg', models.IntegerField()),
                ('total_loss_insert', models.IntegerField()),
                ('total_loss_clean', models.IntegerField()),
                ('total_loss_fill', models.IntegerField()),
                ('total_openEgg', models.IntegerField()),
                ('total_eggUse', models.IntegerField()),
                ('total_storeInsert', models.IntegerField()),
                ('total_produceStore', models.IntegerField()),
                ('total_productAmount', models.IntegerField()),
                ('total_productCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductUnitPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('delete_state', models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2)),
                ('price', models.IntegerField()),
                ('locationCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='core.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='setProductCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('codeName', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('delete_state', models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SetProductMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('delete_state', models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2)),
                ('setProductCode', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='productcode',
            old_name='code_name',
            new_name='codeName',
        ),
        migrations.AddField(
            model_name='productcode',
            name='store_type',
            field=models.CharField(choices=[('AP', 'AP'), ('BIB', 'BIB'), ('CT', 'CT'), ('PAC', 'PAC'), ('PKG', 'PKG'), ('TANK', 'TANK'), ('TON', 'TON'), ('TOTE', 'TOTE'), ('', '없음')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='setproductmatch',
            name='productCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCode'),
        ),
        migrations.AddField(
            model_name='setproductmatch',
            name='saleLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
        migrations.AddField(
            model_name='productunitprice',
            name='productCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.ProductCode'),
        ),
        migrations.AddField(
            model_name='productegg',
            name='master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='product.ProductMaster'),
        ),
    ]
