# Generated by Django 2.0 on 2018-10-04 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181002_1700'),
        ('release', '0001_initial'),
        ('product', '0002_auto_20181004_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadmin',
            name='releaseSeq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.Release'),
        ),
        migrations.AddField(
            model_name='product',
            name='master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_id', to='product.ProductMaster'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchaseLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_locationCode', to='core.Location'),
        ),
    ]
