# Generated by Django 2.0 on 2018-10-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20181008_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='produce_id',
            field=models.IntegerField(default=0),
        ),
    ]
