# Generated by Django 2.0 on 2018-10-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20181008_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productegg',
            name='loss_insert',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productegg',
            name='loss_openEgg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productegg',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productegg',
            name='pastTank_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productegg',
            name='rawTank_amount',
            field=models.IntegerField(default=0),
        ),
    ]
