# Generated by Django 2.0 on 2018-10-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20181012_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='productegg',
            name='delete_state',
            field=models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='delete_state',
            field=models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2),
        ),
    ]
