# Generated by Django 2.0 on 2018-10-25 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20181024_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='setproductmatch',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
