# Generated by Django 2.0 on 2019-01-15 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_auto_20190115_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaster',
            name='delete_state',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='total_eggUse',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='total_openEgg',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='total_produceStore',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='total_productAmount',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='total_productCount',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='total_storeInsert',
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
