# Generated by Django 2.0 on 2019-01-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location_location_owner'),
        ('product', '0069_auto_20190123_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymd', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=255)),
                ('codeName', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('amount_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('delete_state', models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2)),
                ('purchaseYmd', models.CharField(blank=True, max_length=8, null=True)),
                ('purchaseLocationName', models.CharField(blank=True, max_length=255, null=True)),
                ('purchaseSupplyPrice', models.IntegerField(blank=True, null=True)),
                ('purchaseVat', models.IntegerField(blank=True, null=True)),
                ('productCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductCode')),
                ('purchaseLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_locationCode', to='core.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchaseLocation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchaseLocationName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchaseSupplyPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchaseVat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchaseYmd',
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('제품생산', '제품생산'), ('미출고품사용', '미출고품사용')], default='제품생산', max_length=30),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
