# Generated by Django 2.0 on 2019-01-24 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location_location_owner'),
        ('product', '0070_auto_20190124_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoem',
            name='productCode',
        ),
        migrations.RemoveField(
            model_name='productoem',
            name='purchaseLocation',
        ),
        migrations.AddField(
            model_name='product',
            name='purchaseLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_locationCode', to='core.Location'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchaseLocationName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchaseSupplyPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchaseVat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchaseYmd',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('제품생산', '제품생산'), ('미출고품사용', '미출고품사용'), ('OEM', 'OEM')], default='제품생산', max_length=30),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
        migrations.DeleteModel(
            name='ProductOEM',
        ),
    ]
