# Generated by Django 2.0 on 2019-03-27 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0074_auto_20190226_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunitprice',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='productunitprice',
            name='specialPrice',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
