# Generated by Django 2.0 on 2019-02-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_auto_20190228_1502'),
        ('product', '0074_auto_20190226_1311'),
    ]

    operations = [
    ]
