# Generated by Django 2.0 on 2019-03-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0075_auto_20190327_0946'),
        ('product', '0077_merge_20190228_1503'),
    ]

    operations = [
    ]
