# Generated by Django 2.0 on 2019-06-26 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0078_auto_20190625_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='display_state',
            field=models.CharField(choices=[('Y', '진행중'), ('N', '마감')], default='Y', max_length=10),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
