# Generated by Django 2.0 on 2019-07-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location_location_owner'),
        ('product', '0081_auto_20190627_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymd', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=255)),
                ('codeName', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('amount_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('전란', '전란'), ('난백난황', '난백난황')], default='전란', max_length=30)),
                ('display_state', models.CharField(choices=[('Y', '진행중'), ('N', '마감')], default='Y', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOrderPacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderLocationCodeName', models.CharField(blank=True, max_length=255, null=True)),
                ('boxCount', models.IntegerField()),
                ('eaCount', models.IntegerField()),
                ('orderLocationCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
                ('productOrderCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='product.ProductOrder')),
            ],
        ),
        migrations.AddField(
            model_name='productcode',
            name='calculation',
            field=models.CharField(choices=[('order', '주문'), ('store', '주문재고'), ('other', '수기')], default='order', max_length=10),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='productCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCode'),
        ),
    ]
