# Generated by Django 2.0 on 2019-08-06 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0083_auto_20190705_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcode',
            name='calculation',
            field=models.CharField(choices=[('자동', '자동'), ('수동', '수동')], default='order', max_length=10),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
