# Generated by Django 2.0 on 2019-08-28 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0084_auto_20190806_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderpacking',
            name='future_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future', to='product.ProductOrderPacking'),
        ),
        migrations.AddField(
            model_name='productorderpacking',
            name='past_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past', to='product.ProductOrderPacking'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='type',
            field=models.CharField(choices=[('전란', '전란'), ('난백난황', '난백난황'), ('차주재고', '차주재고'), ('전주재고', '전주재고')], default='전란', max_length=30),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
