# Generated by Django 2.0 on 2019-08-29 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0086_auto_20190828_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='future_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='future', to='product.ProductOrder', verbose_name='차주재고'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='past_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past', to='product.ProductOrder', verbose_name='전주재고'),
        ),
        migrations.AlterField(
            model_name='productorderpacking',
            name='future_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='future', to='product.ProductOrderPacking', verbose_name='차주재고'),
        ),
        migrations.AlterField(
            model_name='productorderpacking',
            name='past_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past', to='product.ProductOrderPacking', verbose_name='전주재고'),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
