# Generated by Django 2.0 on 2019-08-30 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0087_auto_20190829_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderpacking',
            name='type',
            field=models.CharField(choices=[('일반', '일반'), ('재고', '재고')], default='일반', max_length=10),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
