# Generated by Django 2.0 on 2019-09-04 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0090_auto_20190904_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delete_state',
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
