# Generated by Django 2.0 on 2020-01-07 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0093_auto_20191114_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setproductmatch',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='setproductmatch',
            name='setProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
