# Generated by Django 2.0 on 2018-11-05 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0013_auto_20181105_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='master_id',
        ),
        migrations.AlterField(
            model_name='release',
            name='releaseSetProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
        migrations.DeleteModel(
            name='ReleaseMaster',
        ),
    ]
