# Generated by Django 2.0 on 2018-11-07 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0016_auto_20181106_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='releaseSetProductCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
        migrations.AlterField(
            model_name='release',
            name='releaseStoreLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_releaseStoreLocation', to='core.Location'),
        ),
    ]
