# Generated by Django 2.0 on 2018-11-16 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0018_auto_20181107_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='releaseSetProductCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
        migrations.AlterField(
            model_name='release',
            name='type',
            field=models.CharField(choices=[('판매', '판매'), ('샘플', '샘플'), ('증정', '증정'), ('자손', '자손'), ('반품', '반품'), ('이동', '이동')], default='판매', max_length=10),
        ),
    ]
