# Generated by Django 2.0 on 2019-03-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0048_auto_20190327_0946'),
        ('release', '0050_merge_20190228_1503'),
    ]

    operations = [
    ]
