# Generated by Django 2.0 on 2019-11-14 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location_location_owner'),
        ('release', '0056_auto_20191114_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('codeName', models.CharField(max_length=255)),
                ('ymd', models.CharField(max_length=8)),
                ('count', models.PositiveIntegerField()),
                ('box', models.PositiveIntegerField()),
                ('ea', models.PositiveIntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_list', to='release.Car')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Location')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_list', to='release.Pallet')),
            ],
        ),
        migrations.AlterField(
            model_name='release',
            name='releaseSetProductCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
