# Generated by Django 2.0 on 2019-12-09 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location_location_owner'),
        ('product', '0087_auto_20191209_1543'),
        ('release', '0058_auto_20190905_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationCodeName', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('codeName', models.CharField(max_length=255)),
                ('ymd', models.CharField(max_length=8)),
                ('count', models.PositiveIntegerField()),
                ('box', models.PositiveIntegerField()),
                ('ea', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet', to='release.Car')),
            ],
        ),
        migrations.AlterField(
            model_name='release',
            name='releaseSetProductCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_list', to='release.Pallet'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='productCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.ProductCode'),
        ),
    ]
