# Generated by Django 2.0 on 2019-11-14 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0059_auto_20191114_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='locationCodeName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='release',
            name='releaseSetProductCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
