# Generated by Django 2.0 on 2018-10-04 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20181002_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymd', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=255)),
                ('codeName', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('memo', models.TextField()),
                ('delete_state', models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2)),
                ('type', models.CharField(choices=[('판매', '판매'), ('샘플', '샘플'), ('증정', '증정'), ('자손', '자손')], default='판매', max_length=10)),
                ('productYmd', models.CharField(max_length=8)),
                ('releaseLocationName', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('releaseOrder', models.CharField(max_length=255)),
                ('releaseStoreLocation', models.CharField(max_length=255)),
                ('releaseSetProductCode', models.CharField(max_length=255)),
                ('releaseVat', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymd', models.CharField(max_length=8)),
                ('totalCount', models.IntegerField()),
                ('totalAmount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='release',
            name='master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_id', to='release.ReleaseMaster'),
        ),
        migrations.AddField(
            model_name='release',
            name='releaseLocationCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_locationCode', to='core.Location'),
        ),
    ]
