# Generated by Django 2.0 on 2018-10-19 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0007_auto_20181016_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasemaster',
            name='delete_state',
            field=models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='release',
            name='releaseSetProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
