# Generated by Django 2.0 on 2018-10-26 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0011_auto_20181019_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='releaseSetProductCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
        migrations.AlterField(
            model_name='releasemaster',
            name='totalAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='releasemaster',
            name='totalCount',
            field=models.IntegerField(default=0),
        ),
    ]
