# Generated by Django 2.0 on 2018-10-04 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20181002_1700'),
        ('release', '0001_initial'),
        ('product', '0003_auto_20181004_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymd', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=255)),
                ('codeName', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('memo', models.TextField()),
                ('delete_state', models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2)),
                ('orderLocationName', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('판매', '판매'), ('샘플', '샘플'), ('증정', '증정'), ('자손', '자손'), ('생산요청', '생산요청')], default='판매', max_length=10)),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymd', models.CharField(max_length=8)),
                ('totalCount', models.IntegerField()),
                ('totalAmount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderMaster'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderLocationCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
        migrations.AddField(
            model_name='order',
            name='release_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release.Release'),
        ),
        migrations.AddField(
            model_name='order',
            name='setProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
