# Generated by Django 2.0 on 2018-11-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20181026_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='master_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='setProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
        migrations.DeleteModel(
            name='OrderMaster',
        ),
    ]
