# Generated by Django 2.0 on 2018-11-20 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20181113_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='specialTag',
            field=models.CharField(choices=[('', '일반'), ('특인가', '특인가')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='setProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
