# Generated by Django 2.0 on 2018-12-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackingCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('codeName', models.CharField(max_length=255)),
                ('delete_state', models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2)),
                ('type', models.CharField(choices=[('입고', '입고'), ('생산', '생산'), ('폐기', '폐기'), ('판매', '판매')], max_length=255)),
                ('packingType', models.CharField(choices=[('포장재', '포장재'), ('외포장재', '외포장재')], max_length=255)),
                ('size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
