# Generated by Django 2.0 on 2018-12-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packingcode',
            name='packingType',
        ),
        migrations.AlterField(
            model_name='packingcode',
            name='type',
            field=models.CharField(choices=[('포장재', '포장재'), ('외포장재', '외포장재')], max_length=255),
        ),
    ]
