# Generated by Django 2.0 on 2018-12-07 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location_location_owner'),
        ('packing', '0003_auto_20181207_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ymd', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=255)),
                ('codeName', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('amount_kg', models.FloatField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('delete_state', models.CharField(choices=[('Y', 'deleted'), ('N', 'notDeleted')], default='N', max_length=2)),
                ('type', models.CharField(choices=[('입고', '입고'), ('생산', '생산'), ('폐기', '폐기'), ('조정', '조정')], max_length=10)),
                ('price', models.IntegerField()),
                ('locationCodeName', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=10, null=True)),
                ('locationCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
                ('packingCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packing.PackingCode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
