# Generated by Django 2.0 on 2018-12-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggcode',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
