# Generated by Django 2.0 on 2018-12-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggs', '0011_auto_20181227_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='ymd',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
