# Generated by Django 2.0 on 2019-02-21 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0054_auto_20190124_1700'),
        ('order', '0054_auto_20190219_1538'),
    ]

    operations = [
    ]
