# Generated by Django 2.0 on 2019-02-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_auto_20190226_1311'),
        ('order', '0057_auto_20190228_1502'),
    ]

    operations = [
    ]
