# Generated by Django 2.0 on 2019-03-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_auto_20190327_0946'),
        ('order', '0058_merge_20190228_1503'),
    ]

    operations = [
    ]
