# Generated by Django 2.0 on 2019-05-06 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0059_merge_20190328_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delete_state',
        ),
        migrations.AlterField(
            model_name='order',
            name='setProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SetProductCode'),
        ),
    ]
